version: "3.9"

services:
  # =========================
  # DATABASES
  # =========================
  postgres-user:
    image: postgres:16
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks: [lms-network]

  postgres-enrollment:
    image: postgres:16
    container_name: postgres-enrollment
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks: [lms-network]

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    networks: [lms-network]

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [lms-network]

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "mongosh", "-u", "admin", "-p", "admin", "--authenticationDatabase", "admin", "--eval", "db.runCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    networks: [lms-network]

  # =========================
  # KEYCLOAK
  # =========================
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    ports:
      - "8086:8080"
    networks: [lms-network]

  # =========================
  # MICROSERVICES
  # =========================
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8087:8086"
    depends_on:
      - keycloak
    networks:
      - lms-network

  user-service:
    build: ./user-service
    image: lms/user-service
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    depends_on:
      postgres-user:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks: [lms-network]

  course-service:
    build: ./course-service
    image: lms/course-service
    environment:
      SERVER_PORT: 8082
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/course_db?authSource=admin
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks: [lms-network]

  enrollment-service:
    build: ./enrollment-service
    image: lms/enrollment-service
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-enrollment:5432/enrollment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_URL: http://user-service:8081
      COURSE_SERVICE_URL: http://course-service:8082
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    depends_on:
      postgres-enrollment:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks: [lms-network]

  payment-service:
    build: ./payment-service
    image: lms/payment-service
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payment:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    depends_on:
      postgres-payment:
        condition: service_healthy
    ports:
      - "8084:8084"
    networks: [lms-network]

  analytics-service:
    build: ./analytics-service
    image: lms/analytics-service
    environment:
      SERVER_PORT: 8085
      ENROLLMENT_SERVICE_URL: http://enrollment-service:8083
      PAYMENT_SERVICE_URL: http://payment-service:8084
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
    ports:
      - "8085:8085"
    networks: [lms-network]

  api-gateway:
    build: ./api-gateway
    image: lms/api-gateway
    environment:
      SERVER_PORT: 8088
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      USER_SERVICE_URL: http://user-service:8081
      COURSE_SERVICE_URL: http://course-service:8082
      ENROLLMENT_SERVICE_URL: http://enrollment-service:8083
      PAYMENT_SERVICE_URL: http://payment-service:8084
      ANALYTICS_SERVICE_URL: http://analytics-service:8085
    depends_on:
      - user-service
      - course-service
      - enrollment-service
      - payment-service
      - analytics-service
      - keycloak
    ports:
      - "8088:8088"
    networks: [lms-network]

  # =========================
  # DEBUGGAGE
  # =========================

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: [ lms-network ]

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    networks: [ lms-network ]



networks:
  lms-network:
    driver: bridge
