server:
  port: 8088

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/lms-realm

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**

        - id: course-service
          uri: http://course-service:8082
          predicates:
            - Path=/courses/**

        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/enrollments/**

        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payments/**

        - id: analytics-service
          uri: http://analytics-service:8085
          predicates:
            - Path=/analytics/**

        - id: auth-service
          uri: http://auth-service:8086
          predicates:
            - Path=/auth/**

