global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8088"]

  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8081"]

  - job_name: "course-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["course-service:8082"]

  - job_name: "enrollment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["enrollment-service:8083"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8084"]

  - job_name: "analytics-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["analytics-service:8085"]
